### PR TITLE
Add integrity attribute for untrusted source

### LINKED ISSUE #318: Fix code scanning alert - Inclusion of functionality from an untrusted source
Tracking issue for:
- [ ] https://github.com/tc39/tc39.github.io/security/code-scanning/1

### PR DESCRIPTION
**Pull request by smorimoto**
Closes #318

### CODE REVIEW

**Comment by smorimoto** [comment]
You can probably use this if you're looking for a tool for reviewing to confirm that the hash is OK: https://www.srihash.org

**Review by DerekNonGeneric — APPROVED** [review]

**Comment by DerekNonGeneric** [comment]
Wonder if we can swap this out for that one by new delegate @LeaVerou (prism)

**Comment by smorimoto** [comment]
I now suspect that this library is no longer used... 🤷‍♂️

**Comment by smorimoto** [comment]
Probably just removing them is enough #321

**Comment by DerekNonGeneric** [comment]
- https://prismjs.com
- https://www.npmjs.com/package/prismjs

🤔

**Comment by smorimoto** [comment]
Sorry! I meant "this library" for the syntax highlighter itself! My poor English! 🤯

**Comment by LeaVerou** [comment]
> Wonder if we can swap this out for that one by new delegate @LeaVerou (prism)

👋🏼

Happy to answer any questions :)

One thing to note that Prism is currently undergoing a rewrite to use ESM (led by @RunDevelopment).

**Pull request closed without merging**
