### PR TITLE
Add links to other tc39 standards in nav

### PR DESCRIPTION
**Pull request by gesa**
Thoughts?

### CODE REVIEW

**Review by chicoxyzzy — APPROVED** [review]
I like this change!

**Comment by littledan** [comment]
I wonder if we might include just 262 and 402

**Comment by gesa** [comment]
@littledan that's totally what i started with. and then i managed to introduce scope creep into a 5-line PR bc I am that good. Anyway I don't have especially strong feelings about it all, feel free to make edits/"suggestions"

**Comment by littledan** [comment]
OK, I removed the others. Does this seem good to land?

**Review by ljharb — APPROVED** [review]

**Review by rkirsling — APPROVED** [review]

**Pull request merged**
