### PR TITLE
Toggle submenu on click menu link text

### LINKED ISSUE #146: mobile menu toggling
- the mobile menu can not be toggled (Samsung Galaxy S7 edge)
- the mobile menu points can not be toggled. (Samsung Galaxy S7 edge and Chrome dev. tools)
-  only interactive when clicking on arrow, the menu text does nothing
- the end of the mobile menu can not be seen clearly when end on white background
- sometimes the mobile menu does not expand with the opened menu points

Annotation 2019-03-22 090337

### PR DESCRIPTION
**Pull request by othree**
Fixes #146 

Didn't call `t.click()` because iOS might disable all these kind of operations(js to mimic user interaction) in the future.

### CODE REVIEW

**Comment by othree** [comment]
Also fix the smooth scroll behavior of menu link.

**Review by littledan — COMMENTED** [review]
This code change makes sense to me and simplifies a bit. Do we have a sense of how compatible it is across browsers?

**Review by littledan — COMMENTED** [review]
This code change makes sense to me and simplifies a bit. Do we have a sense of how compatible it is across browsers?

**Comment by littledan** [comment]
@bkardell, could you review this?

**Comment by codehag** [comment]
@othree - this looks good to me, can you rebase?

**Comment by othree** [comment]
@codehag I have updated the PR. But the CI failed for unknown reason.

**Comment by othree** [comment]
I found its prettier check failed issue.
But the message is not clear.

Should we run prettier manually?
Or use pre-commit hook to handle it(but I saw lint-staged and husky are removed).
Not sure which one is prefered solution.

**Comment by ljharb** [comment]
generally one runs linting/formatting manually.

**Comment by codehag** [comment]
This looks good now, thanks. 

Regarding the prettier question, we can bring it up in the website meeting.

**Pull request merged**
