### PR TITLE
add monthly planning call

### LINKED ISSUE #58: add information about the monthly planning call
What it says on the tin! Many people are unaware of the monthly planning call and that it is open to all. Let's add information about what kind of stuff is discussed and how to join.

### PR DESCRIPTION
**Pull request by codehag**
Fixes #58

I was a bit unsure if we should publish the link here, what do people think?

### CODE REVIEW

**Comment by serspump4299** [comment]
Like

**Review by xtuc — APPROVED** [review]

**Comment by littledan** [comment]
How about, say to email some address to get a link?

**Comment by xtuc** [comment]
> which email would you choose? Mailing list in future?

Maybe a google group? Or I can create a mailing list on `@sauleau.com` but that looks weird.

**Comment by codehag** [comment]
I don't find the email solution to be a good one. I've published my email before and received harassment and spam so I am not willing to use mine. We could set up a dedicated email account that everyone has access to, but my experience with that is that only one or two people check it. How about we publish the url, but you have to knock to get in? That way we could also address them right away

**Comment by littledan** [comment]
I see, apologies for this bad suggestion. Sure, publishing the URL, knocking to get in sounds good (though I'm not a Google Meet expert and I'm not sure how to make sure that they have to do that).

**Pull request merged**
