### PR TITLE
Bump `engines.node` to `>=20`

### PR DESCRIPTION
**Pull request by smorimoto**
This change minimises my concerns, which I tried to address in #354, in a different way as reasonably and acceptably as possible.

### CODE REVIEW

**Comment by smorimoto** [comment]
@ljharb This change does not strictly enforce the npm version, but the narrow lower bound of Node.js restricts the use of a wide range of bundled versions of npm in most scenarios.

**Review by jasonwilliams — APPROVED** [review]
This change is much more preferential to introducing corepack. @smorimoto can I ask the context behind this? Did something break compatibility somewhere?

**Comment by smorimoto** [comment]
@jasonwilliams Some people have experienced lockfile versions being rolled back to the old one due to the old npm version. (and I received some PMs about that 🤷‍♂️)

**Comment by ljharb** [comment]
Totally agree.

You can also set engines.npm if strictly necessary.

**Comment by ljharb** [comment]
and, you can specify lockfileVersion in npmrc.

**Comment by smorimoto** [comment]
> and, you can specify lockfileVersion in npmrc.

Oh, I didn't know about that. I don't really use npm these days, but it seems to be okay to use it recently.

**Comment by smorimoto** [comment]
@ljharb Thank you for the great review to get things moving in a right direction!

**Comment by ljharb** [comment]
It remains as it's always been, the best choice :-)

**Pull request merged**
