### PR TITLE
Fixes #55 - Basic travis configuration for linting

### LINKED ISSUE #55: Add travis configuration
I'd like to have a small travis configuration to (at least) do the linting inside PRs.

### PR DESCRIPTION
**Pull request by Regaddi**
Not sure, if this runs directly or needs more tweaking.

@codehag

### CODE REVIEW

**Comment by ljharb** [comment]
(just as a heads up; putting the issue in the title doesn't do anything; it needs to be in your OP for github to link and autoclose it)

**Comment by Regaddi** [comment]
I am not sure what "OP" means in this context 😐

**Comment by ljharb** [comment]
"Original Post" - ie, the initial comment :-)

**Comment by Regaddi** [comment]
Reading the build log, it shows up current linting errors. Will fix them as part of this PR.

**Comment by Regaddi** [comment]
Should be good now

**Pull request merged**
