### PR TITLE
Correct stage count

### PR DESCRIPTION
**Pull request by mathiasbynens**
Per the referenced process document, there are five stages (not four):

1. Stage 0
2. Stage 1
3. Stage 2
4. Stage 3
5. Stage 4

### CODE REVIEW

**Comment by littledan** [comment]
I don't think Stage 0 is really much of a stage, even if we have documented the term in the process doc. I prefer to continue to refer to it as a four-stage process.

**Comment by jasonwilliams** [comment]
> I don't think Stage 0 is really much of a stage, even if we have documented the term in the process doc. I prefer to continue to refer to it as a four-stage process.

Does that not make this awkward?
https://github.com/tc39/proposals/blob/master/stage-0-proposals.md

**Comment by ljharb** [comment]
@rkirsling hence the two bullet points on the linked document, filtering the list from “uselessly broad” to “useful”

**Comment by bramus** [comment]
The [Process Document](https://tc39.es/process-document/) also states that there are five stages:

> There are five stages: a strawperson stage, and 4 “maturity” stages.

**Comment by mathiasbynens** [comment]
I gotta say, I wasn't expecting this to be controversial...

**Pull request merged**
