### PR TITLE
update stage 3, May 2021

### PR DESCRIPTION
**Pull request by codehag**
Update to stage 3 -- No need for translations if you don't have time for them right now, just a quick check is enough.

### CODE REVIEW

**Comment by smorimoto** [comment]
It might be smoother to translate them in another PR.

**Review by smorimoto — APPROVED** [review]

**Review by chicoxyzzy — APPROVED** [review]
I will find volunteers to help with translation to Russian

**Comment by codehag** [comment]
I'll work soon on making translations less of a pain

**Comment by smorimoto** [comment]
Well, it doesn't really pain that much, so it might be enough just to find someone to translate.

**Comment by DerekNonGeneric** [comment]
@codehag, deployyy.

**Pull request merged**
