### PR TITLE
Added translations for proposals.community_translations

### LINKED ISSUE #320: Add translations for `proposals.community_translations`
### Translation status of each language

At the time this issue was created, work has already been completed in French and Russian, but not yet in the other languages. Anyone interested in working on this, raise your hand on this issue. (To prevent duplication of effort among multiple contributors!)

| Language             | Status | Link                                                                                                            |
| -------------------- | ------ | --------------------------------------------------------------------------------------------------------------- |
| German Translation   | ✅     | https://github.com/tc39/tc39.github.io/blob/be8c92e9363633ae018d814c7da88fea5e728e3c/de/proposals.json#L29      |
| French Translation   | ✅     | https://github.com/tc39/tc39.github.io/blob/be8c92e9363633ae018d814c7da88fea5e728e3c/fr/proposals.json#L29      |
| Japanese Translation | ✅     | https://github.com/tc39/tc39.github.io/blob/be8c92e9363633ae018d814c7da88fea5e728e3c/ja/proposals.json#L29      |
| Russian Translation  | ✅     | https://github.com/tc39/tc39.github.io/blob/be8c92e9363633ae018d814c7da88fea5e728e3c/ru/proposals.json#L29      |
| Simplified Chinese   | ✅     | https://github.com/tc39/tc39.github.io/blob/be8c92e9363633ae018d814c7da88fea5e728e3c/zh-Hans/proposals.json#L29 |

### PR DESCRIPTION
**Pull request by Ritish134**
Added German Translation, Japanese Translation, Traditional Chinese 
Fixes #320

### CODE REVIEW

**Comment by smorimoto** [comment]
How did you translate this? Are you a multilingual? Or did you use machine translation? Please do not use machine translation as we need to guarantee translation quality.

**Comment by smorimoto** [comment]
*Because the translation does not feel very accurate to me.

**Comment by Ritish134** [comment]
> How did you translate this? Are you a multilingual? Or did you use machine translation? Please do not use machine translation as we need to guarantee translation quality.

I used Google Translate

**Comment by smorimoto** [comment]
I appreciate the contribution, but it is difficult to merge this at this point due to quality guarantees.

**Pull request closed without merging**
