### PR TITLE
Update `.nvmrc` to use Node.js 20

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by ctcpip** [comment]
I think this is fine, but why not stick with the active LTS for this?

**Comment by smorimoto** [comment]
I don't have a very strong opinion, but since it's just a runtime for development in a way here, I thought there was no reason to stick to anything too much 🙂

**Comment by ljharb** [comment]
If the intention is to stick to LTS, it shouldn't have `18`, it should have `lts/*` or `lts/hydrogen` :-)

**Comment by ctcpip** [comment]
more of an aside than anything else, but for _reasons_, I always prefer to specify the exact version -- `x.y.z`

but, I am fine with any of the above for this.  will approve as is, but will approve any of these alternatives as well

**Review by ctcpip — APPROVED** [review]

**Comment by smorimoto** [comment]
There is no guarantee that CI will always work well with LTS, so I would just specify the major version here 😑 (As you know, the JS ecosystem grows too fast!)

**Pull request merged**
