### PR TITLE
Tweaked class to current best practice

### PR DESCRIPTION
**Pull request by aardrian**
This better supports wrapping issues that cause pronunciation issues in screen readers.

### CODE REVIEW

**Comment by bkardell** [comment]
It looks like the author has a lint rule set up that fails if the properties you added are not in alpha order @aardrian  

https://travis-ci.com/tc39/tc39.github.io/builds/104949675

**Comment by aardrian** [comment]
@bkardell Dinna notice that. Thanks. Had closed the tab to get back to work and missed the big red X as well.

**Comment by aardrian** [comment]
@bkardell I have no idea what this fail is.

**Comment by littledan** [comment]
Seems like alphabetical order: https://travis-ci.com/tc39/tc39.github.io/builds/104971083#L463

**Comment by othree** [comment]
Move `white-space` before `width` should work (at least on my local machine)

**Comment by aardrian** [comment]
Yeah, bad at alpha today. And reading Travis issues. And paying attention. Anyway, passed all checks.

**Pull request merged**
